// ====================================================================
// Parametric Triple Drone Flute (Uniform Hexagonal Body & Tapered Mouthpiece)
// Generated by flute-generator
// Root Note MIDI: 69
// Total Height: 431.60 mm
// Melody Bore: 19.00 mm, Acoustic Length: 359.60 mm
// Drone 1 Bore: 22.00 mm, Acoustic Length: 354.80 mm
// Drone 2 Bore: 16.00 mm, Acoustic Length: 234.69 mm
// ====================================================================

$fn = 60;

// Dimensional Parameters
wall = 4.00;
spacing = 25.00;
tol = 0.40;

bore_melody = 19.00;
bore_drone1 = 22.00;
bore_drone2 = 16.00;

// Uniform outer body sizing based on maximum bore
outer_d = 30.00;

L_melody = 359.60;
L_drone1 = 354.80;
L_drone2 = 234.69;

head_len = 42.00;
win_len = 5.20;
w_h = 1.35;
total_L = 431.60;
fipple_z = 389.60;

// Mouthpiece convergence parameters
tip_spacing = 10.50;
tip_w = 38.00;
tip_d = 12.00;

// Part selector for 3D printing
print_part = "assembled"; // [assembled, head, mid, foot]

// --------------------------------------------------------------------
// Uniform Hexagonal Body Profile Hull
// --------------------------------------------------------------------
module hex_profile_2d() {
    hull() {
        translate([-spacing, 0]) circle(d=outer_d, $fn=6);
        translate([spacing, 0]) circle(d=outer_d, $fn=6);
        square([spacing*1.5, outer_d * 0.866], center=true);
    }
}

module body_cross_section(h) {
    linear_extrude(height=h) hex_profile_2d();
}

module body_with_chimneys(h) {
    union() {
        // Main body tube from base up to the fipple line
        body_cross_section(fipple_z + win_len);
        
        // Tapered mouthpiece beak lofting from body width inward to compact mouth tip
        hull() {
            translate([0, 0, fipple_z + win_len])
                linear_extrude(height=1) hex_profile_2d();
                
            translate([0, 0, total_L - 1])
                linear_extrude(height=1)
                    hull() {
                        translate([-tip_spacing, 0]) circle(d=tip_d, $fn=6);
                        translate([tip_spacing, 0]) circle(d=tip_d, $fn=6);
                    }
        }

        // Front ergonomic chimney pads for tone holes
        translate([0, outer_d/2 - 0.5, 51.89]) rotate([-90, 0, 0]) cylinder(d1=13.00, d2=9.50, h=3.00, $fn=6);
        translate([0, outer_d/2 - 0.5, 110.46]) rotate([-90, 0, 0]) cylinder(d1=13.00, d2=9.50, h=3.00, $fn=6);
        translate([0, outer_d/2 - 0.5, 127.83]) rotate([-90, 0, 0]) cylinder(d1=13.00, d2=9.50, h=3.00, $fn=6);
        translate([0, outer_d/2 - 0.5, 159.71]) rotate([-90, 0, 0]) cylinder(d1=13.00, d2=9.50, h=3.00, $fn=6);
        translate([0, outer_d/2 - 0.5, 174.32]) rotate([-90, 0, 0]) cylinder(d1=13.00, d2=9.50, h=3.00, $fn=6);
        translate([0, outer_d/2 - 0.5, 201.12]) rotate([-90, 0, 0]) cylinder(d1=13.00, d2=9.50, h=3.00, $fn=6);
        translate([0, outer_d/2 - 0.5, 225.00]) rotate([-90, 0, 0]) cylinder(d1=13.00, d2=9.50, h=3.00, $fn=6);
    }
}

// --------------------------------------------------------------------
// Resonator Bores (start at fipple_z and run downwards to bottom base)
// --------------------------------------------------------------------
module bores() {
    // Internal acoustic chambers
    translate([-spacing, 0, fipple_z - L_drone1]) cylinder(d=bore_drone1, h=L_drone1 + 0.05);
    translate([0, 0, fipple_z - L_melody]) cylinder(d=bore_melody, h=L_melody + 0.05);
    translate([spacing, 0, fipple_z - L_drone2]) cylinder(d=bore_drone2, h=L_drone2 + 0.05);

    // Open bottom exit bores extending down through the base (Z=0)
    translate([-spacing, 0, -1]) cylinder(d=bore_drone1, h=fipple_z - L_drone1 + 1.1);
    translate([0, 0, -1]) cylinder(d=bore_melody, h=fipple_z - L_melody + 1.1);
    translate([spacing, 0, -1]) cylinder(d=bore_drone2, h=fipple_z - L_drone2 + 1.1);
}

// --------------------------------------------------------------------
// Precision Fipple Sound Windows & Converging Airway Windways
// --------------------------------------------------------------------
module fipple_sound_windows() {
    // 1. Drone 1 Window & Labium (Left)
    w_w1 = bore_drone1 * 0.45;
    translate([-spacing, 0, 0]) {
        translate([-w_w1/2, bore_drone1/2 - w_h - 0.2, fipple_z])
            cube([w_w1, outer_d, win_len]);
        translate([-w_w1/2, bore_drone1/2 + 0.1, fipple_z])
            rotate([-35, 0, 0])
                cube([w_w1, outer_d, win_len*1.6]);
    }

    // 2. Melody Window & Labium (Center)
    w_wm = bore_melody * 0.45;
    translate([0, 0, 0]) {
        translate([-w_wm/2, bore_melody/2 - w_h - 0.2, fipple_z])
            cube([w_wm, outer_d, win_len]);
        translate([-w_wm/2, bore_melody/2 + 0.1, fipple_z])
            rotate([-35, 0, 0])
                cube([w_wm, outer_d, win_len*1.6]);
    }

    // 3. Drone 2 Window & Labium (Right)
    w_w2 = bore_drone2 * 0.45;
    translate([spacing, 0, 0]) {
        translate([-w_w2/2, bore_drone2/2 - w_h - 0.2, fipple_z])
            cube([w_w2, outer_d, win_len]);
        translate([-w_w2/2, bore_drone2/2 + 0.1, fipple_z])
            rotate([-35, 0, 0])
                cube([w_w2, outer_d, win_len*1.6]);
    }
}

// Windway height and drone air balancing
w_h_m = w_h;
w_h_d1 = w_h * 0.75;
w_h_d2 = w_h * 0.75;

// Profile selector
windway_profile = "venturi"; // ["flat", "arched", "sac", "venturi"]
windway_texture = "ribbed"; // ["smooth", "ribbed"]

module single_windway(w, h, x_start, x_end, is_drone=false) {
    entry_h = (windway_profile == "venturi") ? h * 1.6 : h;
    
    difference() {
        hull() {
            translate([x_start - w/2, bore_melody/2 - h, fipple_z + win_len - 0.2])
                cube([w, h, 1]);
            translate([x_end - w/2, -entry_h/2, total_L - 0.1])
                cube([w, entry_h, 1.2]);
        }
        
        // Micro-ribbed aeroacoustic texture on drone airways if enabled
        if (is_drone && windway_texture == "ribbed") {
            for (rz = [fipple_z + win_len + 5 : 4 : total_L - 8]) {
                translate([x_start - w/2 - 0.5, bore_melody/2 - h - 0.3, rz])
                    rotate([0, 90, 0])
                        cylinder(r=0.4, h=w + 1, $fn=12);
            }
        }
    }
}

module slow_air_chamber() {
    // Internal expansion reservoir for smoothing breath dynamics & warm attack
    if (windway_profile == "sac") {
        sac_z_start = fipple_z + win_len + 10;
        sac_z_end = total_L - 8;
        hull() {
            translate([-tip_spacing * 0.9, 0, sac_z_start])
                cylinder(d=6.0, h=1, center=true);
            translate([tip_spacing * 0.9, 0, sac_z_start])
                cylinder(d=6.0, h=1, center=true);
            translate([-tip_spacing * 0.9, 0, sac_z_end])
                cylinder(d=7.5, h=1, center=true);
            translate([tip_spacing * 0.9, 0, sac_z_end])
                cylinder(d=7.5, h=1, center=true);
        }
    }
}

module converging_windways() {
    w_wm = bore_melody * 0.45;
    w_w1 = bore_drone1 * 0.45;
    w_w2 = bore_drone2 * 0.45;

    // Melody windway (Center)
    single_windway(w_wm, w_h_m, 0, 0, false);

    // Drone 1 windway (Left)
    single_windway(w_w1, w_h_d1, -spacing, -tip_spacing, true);

    // Drone 2 windway (Right)
    single_windway(w_w2, w_h_d2, spacing, tip_spacing, true);

    // Optional Slow Air Chamber (SAC) expansion bulb
    slow_air_chamber();
}

// --------------------------------------------------------------------
// Complete Flute Assembly
// --------------------------------------------------------------------
module complete_flute() {
    difference() {
        body_with_chimneys(total_L);
        bores();
        fipple_sound_windows();
        converging_windways();
        translate([0, 0, 51.89]) rotate([-90, 0, 0]) cylinder(d=7.00, h=35.00, center=false);
        translate([0, 0, 110.46]) rotate([-90, 0, 0]) cylinder(d=7.00, h=35.00, center=false);
        translate([0, 0, 127.83]) rotate([-90, 0, 0]) cylinder(d=7.00, h=35.00, center=false);
        translate([0, 0, 159.71]) rotate([-90, 0, 0]) cylinder(d=7.00, h=35.00, center=false);
        translate([0, 0, 174.32]) rotate([-90, 0, 0]) cylinder(d=7.00, h=35.00, center=false);
        translate([0, 0, 201.12]) rotate([-90, 0, 0]) cylinder(d=7.00, h=35.00, center=false);
        translate([0, 0, 225.00]) rotate([-90, 0, 0]) cylinder(d=7.00, h=35.00, center=false);
    }
}

// --------------------------------------------------------------------
// Print Slices & Interlocking Joints for 3D Printers
// --------------------------------------------------------------------
slice1_z = total_L * 0.35;
slice2_z = total_L * 0.70;
joint_len = 15;

module foot_slice() {
    difference() {
        intersection() {
            complete_flute();
            translate([0, 0, slice1_z/2]) cube([200, 200, slice1_z], center=true);
        }
        translate([0, 0, slice1_z - joint_len]) body_cross_section(joint_len + 1);
    }
}

module mid_slice() {
    difference() {
        union() {
            intersection() {
                complete_flute();
                translate([0, 0, (slice1_z + slice2_z)/2]) cube([200, 200, slice2_z - slice1_z], center=true);
            }
            translate([0, 0, slice1_z - joint_len])
                intersection() {
                    complete_flute();
                    body_cross_section(joint_len); 
                }
        }
        translate([0, 0, slice2_z - joint_len]) body_cross_section(joint_len + 1);
    }
}

module head_slice() {
    union() {
        intersection() {
            complete_flute();
            translate([0, 0, (slice2_z + total_L)/2]) cube([200, 200, total_L - slice2_z], center=true);
        }
        translate([0, 0, slice2_z - joint_len])
            intersection() {
                complete_flute();
                body_cross_section(joint_len);
            }
    }
}

// Output selection
if (print_part == "assembled") {
    complete_flute();
} else if (print_part == "head") {
    head_slice();
} else if (print_part == "mid") {
    mid_slice();
} else if (print_part == "foot") {
    foot_slice();
}
