"""OpenSCAD 3D model generator for multi-drone flutes with uniform hexagonal outer body, converging mouthpiece beak, and front-only tone holes."""

from pathlib import Path
from typing import Union
from .acoustics import FluteDimensions

WINDWAY_HEIGHT = 1.35       # Windway airway height (mm)
WINDWAY_WIDTH_RATIO = 0.45  # Windway width relative to bore diameter
WINDOW_LENGTH = 5.2         # Fipple sound window length (mm)
LABIUM_ANGLE = 35           # Labium splitting wedge angle (degrees)
HEAD_LENGTH = 42.0          # Head / mouthpiece height above the acoustic origin (fipple)
TIP_SPACING = 10.5          # Converged spacing between windways at the mouthpiece tip (mm)
TIP_WIDTH = 38.0            # Mouthpiece tip width (mm) to comfortably fit the human mouth
TIP_DEPTH = 12.0            # Mouthpiece tip thickness (mm)


def generate_scad_content(dims: FluteDimensions) -> str:
    """Generate parametric OpenSCAD source code with uniform hexagonal body and converging mouthpiece beak."""
    head_len = HEAD_LENGTH
    total_cad_length = head_len + dims.total_length
    fipple_z = total_cad_length - head_len  # Acoustic origin: Z coordinate of the labium splitting edge

    # Maximum bore determines the uniform outer dimension
    max_bore = max(dims.bore_melody, dims.bore_drone1, dims.bore_drone2)
    outer_d = max_bore + dims.wall * 2

    chimneys_scad = []
    holes_scad = []

    for pos in dims.hole_positions:
        # Tone hole Z = fipple splitting edge - acoustic hole distance
        abs_z = fipple_z - pos
        # Ergonomic raised faceted chimney pad on the front (+Y) face
        c_code = (
            f"        translate([0, outer_d/2 - 0.5, {abs_z:.2f}]) rotate([-90, 0, 0]) "
            f"cylinder(d1={dims.hole_diameter + 6:.2f}, d2={dims.hole_diameter + 2.5:.2f}, h={3.0:.2f}, $fn=6);"
        )
        chimneys_scad.append(c_code)

        # Tone hole cut: starts at bore center Y=0 and cuts ONLY forward (+Y) through the front wall!
        # center=false so it NEVER penetrates the back wall!
        h_code = (
            f"        translate([0, 0, {abs_z:.2f}]) rotate([-90, 0, 0]) "
            f"cylinder(d={dims.hole_diameter:.2f}, h={outer_d + 5:.2f}, center=false);"
        )
        holes_scad.append(h_code)

    chimneys_block = "\n".join(chimneys_scad) if chimneys_scad else "        // No tone holes"
    holes_block = "\n".join(holes_scad) if holes_scad else "        // No tone holes"

    scad_template = f"""// ====================================================================
// Parametric Triple Drone Flute (Uniform Hexagonal Body & Tapered Mouthpiece)
// Generated by flute-generator
// Root Note MIDI: {dims.root_midi}
// Total Height: {total_cad_length:.2f} mm
// Melody Bore: {dims.bore_melody:.2f} mm, Acoustic Length: {dims.length_melody:.2f} mm
// Drone 1 Bore: {dims.bore_drone1:.2f} mm, Acoustic Length: {dims.length_drone1:.2f} mm
// Drone 2 Bore: {dims.bore_drone2:.2f} mm, Acoustic Length: {dims.length_drone2:.2f} mm
// ====================================================================

$fn = 60;

// Dimensional Parameters
wall = {dims.wall:.2f};
spacing = {dims.spacing:.2f};
tol = {dims.tolerance:.2f};

bore_melody = {dims.bore_melody:.2f};
bore_drone1 = {dims.bore_drone1:.2f};
bore_drone2 = {dims.bore_drone2:.2f};

// Uniform outer body sizing based on maximum bore
outer_d = {outer_d:.2f};

L_melody = {dims.length_melody:.2f};
L_drone1 = {dims.length_drone1:.2f};
L_drone2 = {dims.length_drone2:.2f};

head_len = {head_len:.2f};
win_len = {WINDOW_LENGTH:.2f};
w_h = {WINDWAY_HEIGHT:.2f};
total_L = {total_cad_length:.2f};
fipple_z = {fipple_z:.2f};

// Mouthpiece convergence parameters
tip_spacing = {TIP_SPACING:.2f};
tip_w = {TIP_WIDTH:.2f};
tip_d = {TIP_DEPTH:.2f};

// Part selector for 3D printing
print_part = "assembled"; // [assembled, head, mid, foot]

// --------------------------------------------------------------------
// Uniform Hexagonal Body Profile Hull
// --------------------------------------------------------------------
module hex_profile_2d() {{
    hull() {{
        translate([-spacing, 0]) circle(d=outer_d, $fn=6);
        translate([spacing, 0]) circle(d=outer_d, $fn=6);
        square([spacing*1.5, outer_d * 0.866], center=true);
    }}
}}

module body_cross_section(h) {{
    linear_extrude(height=h) hex_profile_2d();
}}

module body_with_chimneys(h) {{
    union() {{
        // Main body tube from base up to the fipple line
        body_cross_section(fipple_z + win_len);
        
        // Tapered mouthpiece beak lofting from body width inward to compact mouth tip
        hull() {{
            translate([0, 0, fipple_z + win_len])
                linear_extrude(height=1) hex_profile_2d();
                
            translate([0, 0, total_L - 1])
                linear_extrude(height=1)
                    hull() {{
                        translate([-tip_spacing, 0]) circle(d=tip_d, $fn=6);
                        translate([tip_spacing, 0]) circle(d=tip_d, $fn=6);
                    }}
        }}

        // Front ergonomic chimney pads for tone holes
{chimneys_block}
    }}
}}

// --------------------------------------------------------------------
// Resonator Bores (start at fipple_z and run downwards to bottom base)
// --------------------------------------------------------------------
module bores() {{
    // Internal acoustic chambers
    translate([-spacing, 0, fipple_z - L_drone1]) cylinder(d=bore_drone1, h=L_drone1 + 0.05);
    translate([0, 0, fipple_z - L_melody]) cylinder(d=bore_melody, h=L_melody + 0.05);
    translate([spacing, 0, fipple_z - L_drone2]) cylinder(d=bore_drone2, h=L_drone2 + 0.05);

    // Open bottom exit bores extending down through the base (Z=0)
    translate([-spacing, 0, -1]) cylinder(d=bore_drone1, h=fipple_z - L_drone1 + 1.1);
    translate([0, 0, -1]) cylinder(d=bore_melody, h=fipple_z - L_melody + 1.1);
    translate([spacing, 0, -1]) cylinder(d=bore_drone2, h=fipple_z - L_drone2 + 1.1);
}}

// --------------------------------------------------------------------
// Precision Fipple Sound Windows & Converging Airway Windways
// --------------------------------------------------------------------
module fipple_sound_windows() {{
    // 1. Drone 1 Window & Labium (Left)
    w_w1 = bore_drone1 * {WINDWAY_WIDTH_RATIO:.2f};
    translate([-spacing, 0, 0]) {{
        translate([-w_w1/2, bore_drone1/2 - w_h - 0.2, fipple_z])
            cube([w_w1, outer_d, win_len]);
        translate([-w_w1/2, bore_drone1/2 + 0.1, fipple_z])
            rotate([-{LABIUM_ANGLE}, 0, 0])
                cube([w_w1, outer_d, win_len*1.6]);
    }}

    // 2. Melody Window & Labium (Center)
    w_wm = bore_melody * {WINDWAY_WIDTH_RATIO:.2f};
    translate([0, 0, 0]) {{
        translate([-w_wm/2, bore_melody/2 - w_h - 0.2, fipple_z])
            cube([w_wm, outer_d, win_len]);
        translate([-w_wm/2, bore_melody/2 + 0.1, fipple_z])
            rotate([-{LABIUM_ANGLE}, 0, 0])
                cube([w_wm, outer_d, win_len*1.6]);
    }}

    // 3. Drone 2 Window & Labium (Right)
    w_w2 = bore_drone2 * {WINDWAY_WIDTH_RATIO:.2f};
    translate([spacing, 0, 0]) {{
        translate([-w_w2/2, bore_drone2/2 - w_h - 0.2, fipple_z])
            cube([w_w2, outer_d, win_len]);
        translate([-w_w2/2, bore_drone2/2 + 0.1, fipple_z])
            rotate([-{LABIUM_ANGLE}, 0, 0])
                cube([w_w2, outer_d, win_len*1.6]);
    }}
}}

module converging_windways() {{
    // Melody Windway (Center: angles to center of mouthpiece tip at Y=0)
    w_wm = bore_melody * {WINDWAY_WIDTH_RATIO:.2f};
    hull() {{
        translate([-w_wm/2, bore_melody/2 - w_h, fipple_z + win_len - 0.2])
            cube([w_wm, w_h, 1]);
        translate([-w_wm/2, -w_h/2, total_L - 0.1])
            cube([w_wm, w_h, 1.2]);
    }}

    // Drone 1 Windway (Left: angles inward from -spacing to -tip_spacing, centered at Y=0)
    w_w1 = bore_drone1 * {WINDWAY_WIDTH_RATIO:.2f};
    hull() {{
        translate([-spacing - w_w1/2, bore_drone1/2 - w_h, fipple_z + win_len - 0.2])
            cube([w_w1, w_h, 1]);
        translate([-tip_spacing - w_w1/2, -w_h/2, total_L - 0.1])
            cube([w_w1, w_h, 1.2]);
    }}

    // Drone 2 Windway (Right: angles inward from +spacing to +tip_spacing, centered at Y=0)
    w_w2 = bore_drone2 * {WINDWAY_WIDTH_RATIO:.2f};
    hull() {{
        translate([spacing - w_w2/2, bore_drone2/2 - w_h, fipple_z + win_len - 0.2])
            cube([w_w2, w_h, 1]);
        translate([tip_spacing - w_w2/2, -w_h/2, total_L - 0.1])
            cube([w_w2, w_h, 1.2]);
    }}
}}

// --------------------------------------------------------------------
// Complete Flute Assembly
// --------------------------------------------------------------------
module complete_flute() {{
    difference() {{
        body_with_chimneys(total_L);
        bores();
        fipple_sound_windows();
        converging_windways();
{holes_block}
    }}
}}

// --------------------------------------------------------------------
// Print Slices & Interlocking Joints for 3D Printers
// --------------------------------------------------------------------
slice1_z = total_L * 0.35;
slice2_z = total_L * 0.70;
joint_len = 15;

module foot_slice() {{
    difference() {{
        intersection() {{
            complete_flute();
            translate([0, 0, slice1_z/2]) cube([200, 200, slice1_z], center=true);
        }}
        translate([0, 0, slice1_z - joint_len]) body_cross_section(joint_len + 1);
    }}
}}

module mid_slice() {{
    difference() {{
        union() {{
            intersection() {{
                complete_flute();
                translate([0, 0, (slice1_z + slice2_z)/2]) cube([200, 200, slice2_z - slice1_z], center=true);
            }}
            translate([0, 0, slice1_z - joint_len])
                intersection() {{
                    complete_flute();
                    body_cross_section(joint_len); 
                }}
        }}
        translate([0, 0, slice2_z - joint_len]) body_cross_section(joint_len + 1);
    }}
}}

module head_slice() {{
    union() {{
        intersection() {{
            complete_flute();
            translate([0, 0, (slice2_z + total_L)/2]) cube([200, 200, total_L - slice2_z], center=true);
        }}
        translate([0, 0, slice2_z - joint_len])
            intersection() {{
                complete_flute();
                body_cross_section(joint_len);
            }}
    }}
}}

// Output selection
if (print_part == "assembled") {{
    complete_flute();
}} else if (print_part == "head") {{
    head_slice();
}} else if (print_part == "mid") {{
    mid_slice();
}} else if (print_part == "foot") {{
    foot_slice();
}}
"""
    return scad_template


def save_scad_file(dims: FluteDimensions, output_path: Union[str, Path]) -> Path:
    """Generate and write the OpenSCAD file to output_path."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    content = generate_scad_content(dims)
    path.write_text(content, encoding="utf-8")
    return path
