"""OpenSCAD 3D model generator for multi-drone flutes."""

from pathlib import Path
from typing import Union
from .acoustics import FluteDimensions


def generate_scad_content(dims: FluteDimensions) -> str:
    """Generate parametric OpenSCAD source code for the given flute dimensions."""
    chimneys_scad = []
    holes_scad = []

    for pos in dims.hole_positions:
        # Outward chimney: wider at base, tapering near the finger hole
        c_code = (
            f"        translate([0, 0, {pos:.2f}]) rotate([-90, 0, 0]) "
            f"cylinder(d1={dims.hole_diameter + 8:.2f}, d2={dims.hole_diameter + 3:.2f}, "
            f"h={dims.bore_melody/2 + dims.wall + 3:.2f});"
        )
        chimneys_scad.append(c_code)

        # Tone hole cutting through chimney and bore wall
        h_code = (
            f"        translate([0, 0, {pos:.2f}]) rotate([-90, 0, 0]) "
            f"cylinder(d={dims.hole_diameter:.2f}, h={dims.bore_melody + dims.wall * 4:.2f}, center=true);"
        )
        holes_scad.append(h_code)

    chimneys_block = "\n".join(chimneys_scad) if chimneys_scad else "        // No tone holes"
    holes_block = "\n".join(holes_scad) if holes_scad else "        // No tone holes"

    scad_template = f"""// ====================================================================
// Parametric Multi-Drone Flute
// Generated by flute-generator
// Root Note MIDI: {dims.root_midi}
// Total Body Length: {dims.total_length:.2f} mm
// Melody Bore: {dims.bore_melody:.2f} mm, Length: {dims.length_melody:.2f} mm
// Drone 1 Bore: {dims.bore_drone1:.2f} mm, Length: {dims.length_drone1:.2f} mm
// Drone 2 Bore: {dims.bore_drone2:.2f} mm, Length: {dims.length_drone2:.2f} mm
// ====================================================================

$fn = 60;

// Configuration Parameters
wall = {dims.wall:.2f};
spacing = {dims.spacing:.2f};
tol = {dims.tolerance:.2f};
total_L = {dims.total_length:.2f};

bore_melody = {dims.bore_melody:.2f};
bore_drone1 = {dims.bore_drone1:.2f};
bore_drone2 = {dims.bore_drone2:.2f};

L_melody = {dims.length_melody:.2f};
L_drone1 = {dims.length_drone1:.2f};
L_drone2 = {dims.length_drone2:.2f};

// Part selector for 3D printing
print_part = "assembled"; // [assembled, head, mid, foot]

module body_profile(h) {{
    hull() {{
        translate([-spacing, 0, 0]) cylinder(d=bore_drone1 + wall*2, h=h);
        translate([spacing, 0, 0]) cylinder(d=bore_drone2 + wall*2, h=h);
        translate([0, 0, h/2]) cube([spacing*2.5, bore_melody + wall*1.5, h], center=true);
    }}
}}

module body_with_chimneys(h) {{
    union() {{
        body_profile(h);
{chimneys_block}
    }}
}}

module bores() {{
    translate([-spacing, 0, -1]) cylinder(d=bore_drone1, h=L_drone1 + 1);
    translate([0, 0, -1]) cylinder(d=bore_melody, h=L_melody + 1);
    translate([spacing, 0, -1]) cylinder(d=bore_drone2, h=L_drone2 + 1);
}}

module simple_fipple(offset_x, bore_d) {{
    translate([offset_x, 0, 5]) {{
        intersection() {{
            cylinder(d=bore_d, h=25);
            translate([-bore_d/2, -bore_d/2 + 2, 0]) cube([bore_d, bore_d, 25]);
        }}
        translate([0, bore_d/2, 22]) cube([bore_d*0.6, wall*4, 6], center=true);
        translate([0, bore_d/2 + 1, 28]) rotate([20, 0, 0]) cube([bore_d*0.6, wall*4, 10], center=true);
    }}
}}

module complete_flute() {{
    difference() {{
        body_with_chimneys(total_L);
        bores();
{holes_block}
    }}
    
    simple_fipple(-spacing, bore_drone1);
    simple_fipple(0, bore_melody);
    simple_fipple(spacing, bore_drone2);
}}

// --------------------------------------------------------------------
// Print Slices & Joint Connectors for tall 3D printers
// --------------------------------------------------------------------
slice1_z = total_L * 0.33;
slice2_z = total_L * 0.66;
joint_len = 15;

module head_slice() {{
    difference() {{
        intersection() {{
            complete_flute();
            translate([0, 0, slice1_z/2]) cube([200, 200, slice1_z], center=true);
        }}
        translate([0, 0, slice1_z - joint_len]) body_profile(joint_len + 1);
    }}
}}

module mid_slice() {{
    difference() {{
        union() {{
            intersection() {{
                complete_flute();
                translate([0, 0, (slice1_z + slice2_z)/2]) cube([200, 200, slice2_z - slice1_z], center=true);
            }}
            translate([0, 0, slice1_z - joint_len])
                intersection() {{
                    complete_flute();
                    body_profile(joint_len); 
                }}
        }}
        translate([0, 0, slice2_z - joint_len]) body_profile(joint_len + 1);
    }}
}}

module foot_slice() {{
    union() {{
        intersection() {{
            complete_flute();
            translate([0, 0, (slice2_z + total_L)/2]) cube([200, 200, total_L - slice2_z], center=true);
        }}
        translate([0, 0, slice2_z - joint_len])
            intersection() {{
                complete_flute();
                body_profile(joint_len);
            }}
    }}
}}

// Output selection
if (print_part == "assembled") {{
    complete_flute();
}} else if (print_part == "head") {{
    head_slice();
}} else if (print_part == "mid") {{
    mid_slice();
}} else if (print_part == "foot") {{
    foot_slice();
}}
"""
    return scad_template


def save_scad_file(dims: FluteDimensions, output_path: Union[str, Path]) -> Path:
    """Generate and write the OpenSCAD file to output_path."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    content = generate_scad_content(dims)
    path.write_text(content, encoding="utf-8")
    return path
